services:

  bootnode:
    image: ethereum/client-go:alltools-v1.13.12
    container_name: 'bootnode'
    ports:
      - "30301:30301"
      - "30303:30303"
    command: [ "bootnode", "-nodekeyhex", "${NODE_PRIVATE}", "-verbosity", "3" ]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  rpc-node:
    image: ethereum/client-go:alltools-v1.13.12
    container_name: 'rpc-node'
    volumes:
      - ./node.sh:/node.sh:ro
      - ./genesis.json:/genesis.json:ro
      - ./data/rpc-node:/data
    ports:
      - "8545:8545"
    command: [ "sh", "/node.sh", "enode://${NODE_CONNECTION}@bootnode:0?discport=30301", "30310", "${NETWORK_ID}" ]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  tools:
    image: ethereum/client-go:alltools-v1.13.12
    volumes:
      - ./genesis.json:/genesis.json:ro
    command: [ "sh", "-c", "tail -f /dev/null" ]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


  validator1:
    image: ethereum/client-go:alltools-v1.13.12
    container_name: 'validator1'
    volumes:
      - ./validator.sh:/validator.sh:ro
      - ./keystore/1_2d558F4633FF8011C27401c0070Fd1E981770B94.json:/data/keystore/1_2d558F4633FF8011C27401c0070Fd1E981770B94:ro
      - ./genesis.json:/genesis.json:ro
      - ./data/validator1:/data
    command: [ "sh", "/validator.sh", "${VALIDATOR_PUB_1}", "${VALIDATOR_PW_1}", "enode://${NODE_CONNECTION}@bootnode:0?discport=30301", "30311", "${NETWORK_ID}" ]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  validator2:
    image: ethereum/client-go:alltools-v1.13.12
    container_name: 'validator2'
    volumes:
      - ./validator.sh:/validator.sh:ro
      - ./keystore/2_66DFE79b64F64718430ffc468806FB3E13853651.json:/data/keystore/2_66DFE79b64F64718430ffc468806FB3E13853651:ro
      - ./genesis.json:/genesis.json:ro
      - ./data/validator2:/data
    command: [ "sh", "/validator.sh", "${VALIDATOR_PUB_2}", "${VALIDATOR_PW_2}", "enode://${NODE_CONNECTION}@bootnode:0?discport=30301", "30312", "${NETWORK_ID}" ]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

  validator3:
    image: ethereum/client-go:alltools-v1.13.12
    container_name: 'validator3'
    volumes:
      - ./validator.sh:/validator.sh:ro
      - ./keystore/3_388C9150daea7e36560c6A22A88D6fE7d3749845.json:/data/keystore/3_388C9150daea7e36560c6A22A88D6fE7d3749845:ro
      - ./genesis.json:/genesis.json:ro
      - ./data/validator3:/data
    command: [ "sh", "/validator.sh", "${VALIDATOR_PUB_3}", "${VALIDATOR_PW_3}", "enode://${NODE_CONNECTION}@bootnode:0?discport=30301", "30313", "${NETWORK_ID}" ]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  blockscout-db:
    image: postgres:15-alpine
    restart: always
    container_name: 'blockscout-db'
    command: postgres -c 'max_connections=250'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'blockscout'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./data/blockscout-db:/var/lib/postgresql/data
    ports:
      - 7432:5432
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  blockscout:
    depends_on:
      - blockscout-db
      - rpc-node
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    container_name: 'blockscout'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
        ETHEREUM_JSONRPC_HTTP_URL: rpc-node:8545
        DATABASE_URL: postgresql://postgres:@blockscout-db:5432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        COIN_NAME: "BC4P"
        CHAIN_ID: '123321'
        DISABLE_EXCHANGE_RATES: 'true'
    ports:
      - 4000:4000

  faucet:
    image: eth-faucet
    build: .
    container_name: 'faucet'
    restart: always
    depends_on:
      - rpc-node
    ports:
      - 9000:9000
